<?php
return [
    'admin_dashboard' => 'Dashboard',
    'user_management' => 'User Management',
    'view_roles' => 'View Roles',
    'add_role' => 'Add Role',
    'edit_role' => 'Edit Role',
    'delete_role' => 'Delete Role',
    'view_users' => 'View Users',
    'add_user' => 'Add User',
    'edit_user' => 'Edit User',
    'delete_user' => 'Delete User',
    'my_account' => 'My Account',
    'my_account_view' => 'Account Settings',
    'company_management' => 'Company Management',
    'view_companies' => 'View Companies',
    'add_company' => 'Add Company',
    'edit_company' => 'Edit Company',
    'delete_company' => 'Delete Company',
    'masters' => 'View Masters',
    'regions_management' => 'View Regions',
    'currency_management' => 'View Currency',
    'project_management' => 'View Project',
    'vouchers_management' => 'View Vouchers',
];